MVCGoogleAuth/Models/ErrorViewModel.cs
namespace MVCGoogleAuth.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCGoogleAuth/Models/News.cs
using System.ComponentModel.DataAnnotations;

namespace MVCGoogleAuth.Models
{
    public class News
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }

        public string ImageUrl { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateModified { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public string Author { get; set; }
    }
}

MVCGoogleAuth/Models/NewsDTO.cs
namespace MVCGoogleAuth.Models
{
    public class NewsDTO
    {
        public string? Title { get; set; }
        public string? Content { get; set; }
        public string? ImageUrl { get; set; }
    }
}

MVCGoogleAuth/Controllers/ApiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCGoogleAuth.Models;
using MVCGoogleAuth.Services.Interfaces;

namespace MVCGoogleAuth.Controllers
{
    /// <summary>
    /// API controller for managing news items. Provides CRUD operations.
    /// </summary>
    [Authorize]
    [ApiController]
    public class ApiController : ControllerBase
    {
        private readonly INewsService _newsService;

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiController"/> class.
        /// </summary>
        /// <param name="newsService">The news service to be used for CRUD operations.</param>
        public ApiController(INewsService newsService)
        {
            _newsService = newsService;
        }

        /// <summary>
        /// Gets a list of all news items.
        /// </summary>
        /// <returns>
        /// A list of news items.
        /// </returns>
        /// <response code="200">Returns the list of news items.</response>
        [Route("api/getnews")]
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public IActionResult GetNews()
        {
            return Ok(_newsService.GetNews());
        }

        /// <summary>
        /// Gets a news item selected by id.
        /// </summary>
        /// <param name="id">The id of the news item.</param>
        /// <returns>
        /// A news item.
        /// </returns>
        /// <response code="200">Returns the news item.</response>
        [Route("api/getnews/{id}")]
        [HttpGet]
        public IActionResult GetNewsById(int id)
        {
            return Ok(_newsService.GetNewsById(id));
        }

        /// <summary>
        /// Create a news item with the required contents.
        /// </summary>
        /// <param name="newsDto">The model of the news data transfer object.</param>
        /// <returns>
        /// The created news item.
        /// </returns>
        /// <response code="200">Returns the news item.</response>
        /// <response code="400">Returns an error if the news data is null.</response>
        /// <remarks>
        /// This method also attempts to obtain the username from the HttpContext. 
        /// If the username is not found (e.g., authorization is disabled), 
        /// it defaults to "unidentified user".
        /// </remarks>
        [Route("api/createnews")]
        [HttpPost]
        public IActionResult CreateNews([FromBody] NewsDTO newsDto)
        {
            if (newsDto == null)
            {
                return BadRequest("News data is null");
            }

            string? userName = HttpContext.User.Identity.Name;

            if (userName == null)
            {
                userName = "unidentified user";
            }

            return Ok(_newsService.CreateNews(userName, newsDto));
        }

        /// <summary>
        /// Update a selected news item with the modified contents.
        /// </summary>
        /// <param name="id">The id of the selected news item.</param>
        /// <param name="newsDto">The model of the news data transfer object.</param>
        /// <returns>
        /// The updated news item.
        /// </returns>
        /// <response code="200">Returns the news item.</response>
        [Route("api/updatenews/{id}")]
        [HttpPut]
        public IActionResult UpdateNews(int id, [FromBody] NewsDTO newsDto)
        {
            return Ok(_newsService.UpdateNews(id, newsDto));
        }

        /// <summary>
        /// Delete a selected news item.
        /// </summary>
        /// <param name="id">The id of the selected news item.</param>
        /// <returns>
        /// A boolean value indicating whether the deletion was successful or not.
        /// </returns>
        /// <response code="200">Returns true if the news item was successfully deleted.</response>
        /// <response code="404">Returns a message if the news with the given ID was not found.</response>
        [Route("api/deletenews/{id}")]
        [HttpDelete]
        public IActionResult DeleteNews(int id)
        {
            bool isDeleted = _newsService.DeleteNews(id);
            if (isDeleted)
            {
                return Ok(isDeleted);
            }
            return NotFound("News with the given ID was not found.");
        }
    }
}

MVCGoogleAuth/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCGoogleAuth.Models;
using System.Diagnostics;

namespace MVCGoogleAuth.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCGoogleAuth/Controllers/ManageNewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVCGoogleAuth.Controllers
{
    public class ManageNewsController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCGoogleAuth/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome in the Google Auth test project.</h1>
    <br />
    <h2>To test the functions of backend with news, click on the button below.</h2>
    <br />
    <br />
    <a href="@Url.Action("Index", "ManageNews")" class="btn btn-primary">Go to Manage News</a>
</div>

MVCGoogleAuth/Views/ManageNews/Index.cshtml
@{
    ViewData["Title"] = "Manage News";
}

<div class="text-center">
    <h1 class="display-4">Manage News</h1>
</div>
<div>
    <form id="newsForm">
        <label for="title">Title</label>
        <input type="text" id="title" name="title">

        <label for="content">Content</label>
        <textarea id="content" name="content"></textarea>

        <label for="title">ImageUrl</label>
        <input type="text" id="imageurl" name="imageurl">

        <button id="subbutton" type="submit">Add News</button>
    </form>
    <p></p>
    <h1>Saved News: </h1>
    <h5> (Add a few news)</h5>
    <p></p>
    <div id="newsList">
    </div>
</div>

<script src="~/js/ManageNews.js"></script>

MVCGoogleAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCGoogleAuth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCGoogleAuth.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCGoogleAuth</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageNews" asp-action="Index">Manage News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCGoogleAuth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>